services:
  aicetgpt:
    image: public.ecr.aws/s2l0n1t2/aicetgpt-repo:aug-18
    container_name: aicetgpt-repo
    ports:
      - "80:8080"
      - "5432:5432"
    environment:
      - "ENABLE_OLLAMA_API=false"
      - "SCARF_NO_ANALYTICS=true"
      - "DO_NOT_TRACK=true"
      - "ANONYMIZED_TELEMETRY=false"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
      - "DATABASE_URL=${DATABASE_URL}"
    restart: unless-stopped
